# python_test
100500 - ая попытка )) 
Вроде бы не все так страшно
